# Generated by Django 6.0.4 on 2026-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
