# Generated by Django 6.0.4 on 2026-05-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAutosave',
        ),
    ]
