# Generated by Django 6.0.4 on 2026-05-17 09:52

from django.conf import settings
from django.db import migrations, models

def delete_null_user_categories(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    Category.objects.filter(user__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_null_user_categories),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_user_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_category_name'),
        ),
    ]
