# Generated by Django 6.0.4 on 2026-05-17 10:01

from django.db import migrations


def delete_null_user_categories(apps, schema_editor):
    Category = apps.get_model('blog', 'Category')
    deleted, _ = Category.objects.filter(user__isnull=True).delete()
    if deleted:
        print(f"  Deleted {deleted} legacy categories with no user.")


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_null_user_categories),
    ]
